# docker-compose.yml
version: '1'
services:
  react-app:
    build:
      context: ./react-app
    container_name: react_app
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"   # Exposing port 80 of NGINX to 8080 of the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react-app
