# docker-compose.yml

services:
    react-app:
        build:
            context: ./react-app
        container_name: react_app
        ports:
            - "3000:3000"

    nginx:
        image: nginx:latest
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - /etc/nginx/ssl:/etc/nginx/ssl:ro # Mount SSL certificates
        depends_on:
            - react-app
